# Generated by Django 4.0.5 on 2022-06-08 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imdb_title_id', models.CharField(max_length=128)),
                ('original_title', models.CharField(max_length=128)),
                ('year', models.IntegerField()),
                ('genre', models.CharField(max_length=128)),
                ('duration', models.IntegerField()),
                ('director', models.CharField(max_length=128)),
                ('writer', models.CharField(max_length=128)),
                ('production_company', models.CharField(max_length=128)),
                ('actors', models.CharField(max_length=128)),
                ('description', models.TextField()),
                ('avg_vote', models.FloatField()),
                ('votes', models.IntegerField()),
            ],
        ),
    ]
