# Generated by Django 4.0.5 on 2022-06-09 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('second', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='post',
            new_name='movie',
        ),
    ]
